### ISSUE TITLE
Port forwarding translation

### ISSUE THREAD

**Issue by mintjustin** [imjuzcy/pia-posh#1]
Are you still able to translate port forwarding script?

**Comment by imjuzcy** [comment]
Because I don't use port forwarding and also I have since switched to Linux full time, I sort of have put that on hold. I will try to translate it when I got time to do it.

**Comment by imjuzcy** [comment]
I have translated the port forwarding script in the port-forwarding branch. Please try it and give some feedbacks regarding if it works for you or not

**Comment by mintjustin** [comment]
Works solid so far. Thank you very much :)
